name: 'RSpec Test Report'
description: 'Reports rspec test results.'
author: 'Hipcamp'
inputs:
  paths:
    required: true
    description: 'the paths to find completed rspec test results'
runs:
  using: 'node12'
  main: 'dist/index.js'
